//! # Mini-grep
//!
//! `minigrep` is a test project derived from rust documentation at:
//!     <https://doc.rust-lang.org/book/ch12-00-an-io-project.html>
//!
//! This document is generated by:
//!
//! ```sh
//! cargo doc
//! ```
//!

mod utils;
pub use utils::Config;
pub use utils::run;

#[cfg(test)]
mod myunits;

